import type { Metadata } from "next";
import "./globals.css";
import { ApolloWrapper } from "@/lib/gpl-wrapper";
import { Navigation } from "@/components/template/sidebar";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button";
import { auth } from "@/auth";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { AvatarMenu } from "@/components/tools/avatar-menu";
import SignIn from "@/components/sing-in";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/file.svg",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} `}>
        <header className=" flex bg-secondary gap-5 p-5 justify-end flex-row ">
          {session?.user ? (
            <AvatarMenu user={session?.user}>
              <section className="flex gap-4">
                <Avatar className="h-8 w-8 rounded-lg">
                  <AvatarImage
                    src={session?.user?.image}
                    alt={session?.user.name}
                  />
                  <AvatarFallback className="rounded-lg">CN</AvatarFallback>
                </Avatar>
                <div className="grid flex-1 text-left text-sm leading-tight">
                  <span className="truncate font-semibold">
                    {session?.user.name}
                  </span>
                  <span className="truncate text-xs">
                    {session?.user.email}
                  </span>
                </div>
              </section>
            </AvatarMenu>
          ) : (
            <Button asChild>
              <SignIn />
            </Button>
          )}
        </header>
        <div className="h-screen flex flex-col md:flex-row bg-background text-foreground items-center ">
          <SessionProvider>
          <Navigation />
            <ApolloWrapper>{children}</ApolloWrapper>
          </SessionProvider>
          <Toaster />
        </div>
        <footer className="bg-secondary py-4 text-center text-secondary-foreground">
          <p>Brandon Quintero 2025</p>
        </footer>
      </body>
    </html>
  );
}
